### ISSUE TITLE
index does not show list of saved queries

### ISSUE THREAD

**Issue by bitcoder** [esminc/adhoq#47]
If you go to either of the following addresses, you won't be able to see the list of saved queries.

http://127.0.0.1:3000/adhoq/
http://127.0.0.1:3000/adhoq/q

In fact, http://127.0.0.1:3000/adhoq/q shows the last saved query..

**Comment by moro** [comment]
Yes. As you say, this version pick `queries.first` every time :skull: 
I'm working on #50 and will resolve these problems.

Thanks.

**Comment by moro** [comment]
Fixed in current master. Please try it again!
